recaptcha:
  site_key: <%= ENV['RECAPTCHA_SITE_KEY'] %>
  secret_key: <%= ENV['RECAPTCHA_SECRET_KEY'] %>
aws:
  key_id: <%= ENV['AWS_KEY_ID'] %>
  secret_key: <%= ENV['AWS_SECRET_KEY'] %>
  bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>
  region: <%= ENV['AWS_REGION'] %>
